//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener.БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.FullName = "";
            this.SalaryFrom = 0;
            this.Schedule = "";
            this.Trips = false;
            this.About = "";
            this.Rate = 0D;
            this.SalaryTo = 0;
            this.IsOwn = false;
            this.ProfileToPosition = new HashSet<ProfileToPosition>();
        }
    
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public long SalaryFrom { get; set; }
        public string Schedule { get; set; }
        public bool Trips { get; set; }
        public string About { get; set; }
        public double Rate { get; set; }
        public System.DateTimeOffset DateOff { get; set; }
        public long SalaryTo { get; set; }
        public bool IsOwn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileToPosition> ProfileToPosition { get; set; }
    }
}
