//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener.БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.FullName = "";
            this.PhoneNumer = "";
            this.Email = "";
            this.Sex = false;
            this.Education = "";
            this.MaritalStatus = "";
            this.City = "";
            this.Сitizen = "";
            this.About = "";
            this.ResumeLink = "";
            this.Interviews = "";
            this.IsReadyToTrips = false;
            this.SalaryTo = 0;
            this.SalaryFrom = 0;
            this.ProfileToPosition = new HashSet<ProfileToPosition>();
            this.Experience = new HashSet<Experience>();
        }
    
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public System.DateTimeOffset BirthDate { get; set; }
        public string PhoneNumer { get; set; }
        public string Email { get; set; }
        public bool Sex { get; set; }
        public string Education { get; set; }
        public string MaritalStatus { get; set; }
        public string City { get; set; }
        public byte[] Photo { get; set; }
        public string Сitizen { get; set; }
        public string About { get; set; }
        public System.DateTimeOffset DateOff { get; set; }
        public bool Responed { get; set; }
        public string ResumeLink { get; set; }
        public string Interviews { get; set; }
        public bool IsReadyToTrips { get; set; }
        public long SalaryTo { get; set; }
        public long SalaryFrom { get; set; }
        public string Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileToPosition> ProfileToPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience> Experience { get; set; }
    }
}
