//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener.БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileToPosition
    {
        public System.Guid Id { get; set; }
        public System.Guid ProfileId { get; set; }
        public System.Guid PositionId { get; set; }
        public System.DateTimeOffset DateOff { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Position Position { get; set; }
    }
}
