//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.ExpTime = "";
        }
    
        public System.Guid Id { get; set; }
        public System.Guid LoginId { get; set; }
        public System.Guid SessionKey { get; set; }
        public string ExpTime { get; set; }
    
        public virtual Logins Logins { get; set; }
    }
}
