//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener.БД
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDBContainer : DbContext
    {
        public UserDBContainer()
            : base("name=UserDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logins> LoginsSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
        public virtual DbSet<Profile> ProfileSet { get; set; }
        public virtual DbSet<ProfileToPosition> ProfileToPositionSet { get; set; }
        public virtual DbSet<Experience> ExperienceSet { get; set; }
    }
}
