//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpListener
{
    using httpListener.БД;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDBContainer : DbContext
    {
        public UserDBContainer()
            : base("name=UserDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logins> LoginsSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
        public virtual DbSet<Profile> ProfileSet { get; set; }
        public virtual DbSet<ProfileToPosition> ProfileToPositionSet { get; set; }
    }
}
